require('dotenv').config()
const mongoose = require('mongoose')
const Property = require('./models/Property')

const properties = [
  {
    title: "Villa de prestige à Gammarth",
    titleFr: "Villa de prestige à Gammarth",
    titleEn: "Prestige Villa in Gammarth",
    description: "Magnifique villa de standing située dans le quartier résidentiel de Gammarth. Vue panoramique sur mer, piscine privée, jardin paysager. Finitions haut de gamme, matériaux nobles. Idéale pour une résidence principale ou secondaire.",
    descriptionFr: "Magnifique villa de standing située dans le quartier résidentiel de Gammarth. Vue panoramique sur mer, piscine privée, jardin paysager. Finitions haut de gamme, matériaux nobles. Idéale pour une résidence principale ou secondaire.",
    descriptionEn: "Magnificent high-end villa located in the residential area of Gammarth. Panoramic sea view, private pool, landscaped garden. High-end finishes, noble materials. Ideal for a primary or secondary residence.",
    type: "sale",
    saleType: "immediate",
    propertyType: "villa",
    status: "available",
    price: 2900000,
    surface: 500,
    rooms: 5,
    bathrooms: 4,
    floor: 0,
    parking: true,
    furnished: false,
    location: { address: "Rue des Jasmins", city: "Gammarth", governorate: "Tunis", lat: 36.9081, lng: 10.2851 },
    amenities: ["Piscine", "Jardin", "Parking", "Climatisation", "Sécurité", "Vue mer"],
    images: [
      { url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80" },
      { url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80" },
      { url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80" },
    ],
    isVerified: true,
    isFeatured: true,
    views: 142,
  },
  {
    title: "Résidence haut standing à Ennasr",
    titleFr: "Résidence haut standing à Ennasr",
    titleEn: "High-end Residence in Ennasr",
    description: "Appartements neufs de 2 à 3 pièces dans une résidence sécurisée avec piscine commune, parking souterrain et gardiennage 24h/24. Livraison 2025.",
    descriptionFr: "Appartements neufs de 2 à 3 pièces dans une résidence sécurisée avec piscine commune, parking souterrain et gardiennage 24h/24. Livraison 2025.",
    descriptionEn: "New 2 to 3 bedroom apartments in a secure residence with shared pool, underground parking and 24/7 security. Delivery 2025.",
    type: "sale",
    saleType: "sur-plan",
    propertyType: "apartment",
    status: "available",
    price: 240000,
    surface: 120,
    rooms: 3,
    bathrooms: 2,
    parking: true,
    furnished: false,
    location: { address: "Avenue Ennasr", city: "Ariana", governorate: "Ariana", lat: 36.8806, lng: 10.1897 },
    amenities: ["Piscine", "Parking", "Ascenseur", "Sécurité", "Gardien"],
    images: [
      { url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80" },
      { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80" },
    ],
    isVerified: true,
    isFeatured: true,
    views: 98,
  },
  {
    title: "Appartement S+2 aux Berges du Lac",
    titleFr: "Appartement S+2 aux Berges du Lac",
    titleEn: "S+2 Apartment at Les Berges du Lac",
    description: "Bel appartement S+2 entièrement rénové et bien situé à La Marsa. Proche de la plage et des commerces. Disponible immédiatement.",
    descriptionFr: "Bel appartement S+2 entièrement rénové et bien situé aux Berges du Lac. Proche de toutes commodités. Disponible immédiatement.",
    descriptionEn: "Beautiful fully renovated S+2 apartment well located at Les Berges du Lac. Close to all amenities. Available immediately.",
    type: "rent",
    rentType: "long-term",
    propertyType: "apartment",
    status: "available",
    price: 2200,
    surface: 110,
    rooms: 2,
    bathrooms: 1,
    floor: 3,
    parking: false,
    furnished: true,
    location: { address: "Rue du Lac Malaren", city: "Les Berges du Lac", governorate: "Tunis", lat: 36.8370, lng: 10.2360 },
    amenities: ["Climatisation", "Internet haut débit", "Ascenseur", "Meublé", "Balcon"],
    images: [
      { url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80" },
      { url: "https://images.unsplash.com/photo-1560448075-bb485b067938?w=800&q=80" },
      { url: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80" },
    ],
    isVerified: true,
    isFeatured: true,
    views: 215,
  },
  {
    title: "Maison moderne à La Marsa",
    titleFr: "Maison moderne à La Marsa",
    titleEn: "Modern House in La Marsa",
    description: "Maison individuelle moderne avec architecture contemporaine. Grand salon, 4 chambres, 3 salles de bain, cuisine américaine équipée, terrasse de 80m².",
    descriptionFr: "Maison individuelle moderne avec architecture contemporaine. Grand salon, 4 chambres, 3 salles de bain, cuisine américaine équipée, terrasse de 80m².",
    descriptionEn: "Modern detached house with contemporary architecture. Large living room, 4 bedrooms, 3 bathrooms, equipped American kitchen, 80m² terrace.",
    type: "sale",
    saleType: "immediate",
    propertyType: "house",
    status: "available",
    price: 1600000,
    surface: 320,
    rooms: 4,
    bathrooms: 3,
    floor: 0,
    parking: true,
    furnished: false,
    location: { address: "Rue de la Corniche", city: "La Marsa", governorate: "Tunis", lat: 36.8786, lng: 10.3228 },
    amenities: ["Terrasse", "Jardin", "Parking", "Climatisation", "Cuisine équipée"],
    images: [
      { url: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80" },
      { url: "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&q=80" },
      { url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80" },
    ],
    isVerified: true,
    isFeatured: true,
    views: 87,
  },
  {
    title: "Appartement S+2 à La Marsa",
    titleFr: "Appartement S+2 à La Marsa",
    titleEn: "S+2 Apartment in La Marsa",
    description: "Appartement lumineux S+2 situé au cœur de La Marsa. Vue dégagée, proche mer et centre commercial. Idéal pour investissement locatif.",
    descriptionFr: "Appartement lumineux S+2 situé au cœur de La Marsa. Vue dégagée, proche mer et centre commercial.",
    descriptionEn: "Bright S+2 apartment located in the heart of La Marsa. Open view, close to the sea and shopping center.",
    type: "sale",
    saleType: "immediate",
    propertyType: "apartment",
    status: "available",
    price: 200000,
    surface: 100,
    rooms: 2,
    bathrooms: 1,
    floor: 2,
    parking: false,
    furnished: false,
    location: { address: "Avenue Habib Bourguiba", city: "La Marsa", governorate: "Tunis", lat: 36.8772, lng: 10.3201 },
    amenities: ["Balcon", "Ascenseur", "Climatisation"],
    images: [
      { url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80" },
      { url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80" },
    ],
    isVerified: true,
    isFeatured: true,
    views: 63,
  },
  {
    title: "Villa avec piscine à Gammarth",
    titleFr: "Villa avec piscine à Gammarth",
    titleEn: "Villa with Pool in Gammarth",
    description: "Superbe villa avec grande piscine à débordement, 4 suites parentales, salle de sport, dépendance gardien. Quartier calme et sécurisé.",
    descriptionFr: "Superbe villa avec grande piscine à débordement, 4 suites parentales, salle de sport, dépendance gardien. Quartier calme et sécurisé.",
    descriptionEn: "Superb villa with large infinity pool, 4 master suites, gym, caretaker's lodge. Quiet and secure neighborhood.",
    type: "rent",
    rentType: "long-term",
    propertyType: "villa",
    status: "available",
    price: 2300,
    surface: 300,
    rooms: 4,
    bathrooms: 2,
    floor: 0,
    parking: true,
    furnished: true,
    location: { address: "Cité Gammarth Supérieur", city: "Gammarth", governorate: "Tunis", lat: 36.9168, lng: 10.2924 },
    amenities: ["Piscine", "Jardin", "Parking", "Climatisation", "Meublé", "Sécurité"],
    images: [
      { url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80" },
      { url: "https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&q=80" },
      { url: "https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=800&q=80" },
    ],
    isVerified: true,
    isFeatured: true,
    views: 178,
  },
  {
    title: "Résidence Elya – Ennasr",
    titleFr: "Résidence Elya – Ennasr",
    titleEn: "Elya Residence – Ennasr",
    description: "Appartements S+1, S+2, S+3 sur plan dans la résidence Elya. Finitions premium, espaces verts, parking. Livraison fin 2025.",
    descriptionFr: "Appartements S+1, S+2, S+3 sur plan dans la résidence Elya. Finitions premium, espaces verts, parking. Livraison fin 2025.",
    descriptionEn: "S+1, S+2, S+3 off-plan apartments in Elya Residence. Premium finishes, green spaces, parking. Delivery end of 2025.",
    type: "sale",
    saleType: "sur-plan",
    propertyType: "apartment",
    status: "available",
    price: 240000,
    surface: 95,
    rooms: 3,
    bathrooms: 1,
    parking: true,
    furnished: false,
    location: { address: "Rue Ennasr 2", city: "Ariana", governorate: "Ariana", lat: 36.8856, lng: 10.1924 },
    amenities: ["Parking", "Ascenseur", "Sécurité", "Jardin"],
    images: [
      { url: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80" },
      { url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&q=80" },
    ],
    isVerified: true,
    isFeatured: true,
    views: 112,
  },
  {
    title: "Appartement S+3 à Sousse",
    titleFr: "Appartement S+3 à Sousse",
    titleEn: "S+3 Apartment in Sousse",
    description: "Grand appartement S+3 bien exposé, vue mer, à 200m de la plage. Résidence sécurisée, piscine commune, parking.",
    descriptionFr: "Grand appartement S+3 bien exposé, vue mer, à 200m de la plage. Résidence sécurisée, piscine commune, parking.",
    descriptionEn: "Large well-exposed S+3 apartment, sea view, 200m from the beach. Secure residence, shared pool, parking.",
    type: "sale",
    saleType: "immediate",
    propertyType: "apartment",
    status: "available",
    price: 360000,
    surface: 150,
    rooms: 3,
    bathrooms: 2,
    floor: 4,
    parking: true,
    furnished: false,
    location: { address: "Boulevard 14 Janvier", city: "Sousse", governorate: "Sousse", lat: 35.8256, lng: 10.6369 },
    amenities: ["Vue mer", "Piscine", "Parking", "Ascenseur", "Balcon"],
    images: [
      { url: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&q=80" },
      { url: "https://images.unsplash.com/photo-1560448205-4d9b3e6bb6db?w=800&q=80" },
    ],
    isVerified: true,
    isFeatured: true,
    views: 94,
  },
  {
    title: "Local commercial à Tunis Centre",
    titleFr: "Local commercial à Tunis Centre",
    titleEn: "Commercial Space in Tunis Centre",
    description: "Local commercial en rez-de-chaussée de 80m² idéalement situé avenue Habib Bourguiba. Fort passage piéton. Idéal boutique, agence ou restauration.",
    descriptionFr: "Local commercial en rez-de-chaussée de 80m² idéalement situé avenue Habib Bourguiba. Fort passage piéton.",
    descriptionEn: "80m² ground floor commercial space ideally located on Avenue Habib Bourguiba. High foot traffic. Ideal for shop, agency or restaurant.",
    type: "rent",
    rentType: "long-term",
    propertyType: "commercial",
    status: "available",
    price: 1400,
    surface: 80,
    rooms: 1,
    bathrooms: 1,
    floor: 0,
    parking: false,
    furnished: false,
    location: { address: "Avenue Habib Bourguiba", city: "Tunis Centre", governorate: "Tunis", lat: 36.7992, lng: 10.1801 },
    amenities: ["Climatisation", "Internet haut débit"],
    images: [
      { url: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80" },
      { url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80" },
    ],
    isVerified: true,
    isFeatured: true,
    views: 55,
  },
  {
    title: "Duplex de luxe à Carthage",
    titleFr: "Duplex de luxe à Carthage",
    titleEn: "Luxury Duplex in Carthage",
    description: "Duplex d'exception sur 2 niveaux dans le quartier historique de Carthage. Terrasse panoramique 60m², 5 chambres, home cinéma, conciergerie.",
    descriptionFr: "Duplex d'exception sur 2 niveaux dans le quartier historique de Carthage. Terrasse panoramique 60m², 5 chambres, home cinéma, conciergerie.",
    descriptionEn: "Exceptional 2-level duplex in the historic district of Carthage. 60m² panoramic terrace, 5 bedrooms, home cinema, concierge service.",
    type: "sale",
    saleType: "immediate",
    propertyType: "apartment",
    status: "available",
    price: 1200000,
    surface: 280,
    rooms: 5,
    bathrooms: 3,
    floor: 8,
    parking: true,
    furnished: true,
    location: { address: "Résidence Carthage Palace", city: "Carthage", governorate: "Tunis", lat: 36.8528, lng: 10.3261 },
    amenities: ["Terrasse", "Piscine", "Parking", "Ascenseur", "Climatisation", "Vue mer", "Sécurité"],
    images: [
      { url: "https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800&q=80" },
      { url: "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&q=80" },
      { url: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&q=80" },
    ],
    isVerified: true,
    isFeatured: true,
    views: 203,
  },
  {
    title: "Appartement S+1 à Sfax",
    titleFr: "Appartement S+1 à Sfax",
    titleEn: "S+1 Apartment in Sfax",
    description: "Appartement S+1 moderne dans résidence neuve au cœur de Sfax. Idéal pour jeune couple ou investissement.",
    descriptionFr: "Appartement S+1 moderne dans résidence neuve au cœur de Sfax. Idéal pour jeune couple ou investissement.",
    descriptionEn: "Modern S+1 apartment in new residence in the heart of Sfax. Ideal for young couple or investment.",
    type: "rent",
    rentType: "long-term",
    propertyType: "apartment",
    status: "available",
    price: 750,
    surface: 65,
    rooms: 1,
    bathrooms: 1,
    floor: 1,
    parking: false,
    furnished: true,
    location: { address: "Route de Tunis", city: "Sfax", governorate: "Sfax", lat: 34.7406, lng: 10.7603 },
    amenities: ["Climatisation", "Meublé", "Ascenseur"],
    images: [
      { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80" },
      { url: "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&q=80" },
    ],
    isVerified: true,
    isFeatured: false,
    views: 41,
  },
  {
    title: "Terrain constructible à Nabeul",
    titleFr: "Terrain constructible à Nabeul",
    titleEn: "Building Plot in Nabeul",
    description: "Terrain constructible de 800m² dans une zone résidentielle calme de Nabeul. Toutes commodités à proximité, titre foncier propre.",
    descriptionFr: "Terrain constructible de 800m² dans une zone résidentielle calme de Nabeul. Toutes commodités à proximité, titre foncier propre.",
    descriptionEn: "800m² building plot in a quiet residential area of Nabeul. All amenities nearby, clean title deed.",
    type: "sale",
    saleType: "immediate",
    propertyType: "terrain",
    status: "available",
    price: 180000,
    surface: 800,
    location: { address: "Zone Résidentielle Mrezga", city: "Nabeul", governorate: "Nabeul", lat: 36.4566, lng: 10.7376 },
    amenities: [],
    images: [
      { url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80" },
    ],
    isVerified: true,
    isFeatured: false,
    views: 29,
  },
]

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI)
    console.log('Connected to MongoDB')

    await Property.deleteMany({})
    console.log('Cleared existing properties')

    const inserted = await Property.insertMany(properties)
    console.log(`✅ Inserted ${inserted.length} properties`)

    inserted.forEach(p => console.log(` - ${p.title} (${p.type}, ${p.price} TND)`))
  } catch (err) {
    console.error('Seed error:', err)
  } finally {
    await mongoose.disconnect()
    console.log('Done.')
  }
}

seed()
